config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy]
  end
  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
    resources :likes, only: [:create]
  end

  #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  
  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  # Associations
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :user_id
  has_many :likes, foreign_key: :user_id

  # Attributes
  attribute :name, :string
  attribute :photo, :string
  attribute :bio, :text
  attribute :posts_counter, :integer, default: 0

  # Validations
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  # Methods
  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<header>
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
</header>
<body>
<div id="user"> 
  <img id="user-image" src="<%= user.photo %>" alt="User Photo">
  <article id="user-details">
    <h1><%= user.name %></h1>
    <p>Number of posts: <%= user.posts_counter.nil? ? 0 : user.posts_counter %></p>
  <article>
</div>
</body>

app/views/users/index.html.erb
<nav class="nav">
  <% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to 'Login', new_user_session_path %>
  <% end %>
  <%= link_to 'Sign Up', new_user_registration_path %>
</nav>
<%= "No users" if @users.empty? %>
<% @users.each do |user| %>
    <a href="<%= user_path(user) %>"><%= render user%></a>
    <br>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>

<nav class="nav">
    <%= link_to "Add New Post", new_user_post_path(@user.id) %>
    <%= link_to "Home", root_path %>
    <%= link_to "Back", :back %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
</nav>

<%= render @user%>
<div id="bio">
 Bio: <%= @user.bio %>
 </div>
<br>
<%='No posts for this user' if (@user.posts.empty?) %>
<% @user.three_most_recent_posts.each do |post| %>
<a href ="<%= user_post_path(@user, post)%>">
  <%= render post %>
<% end %>
<div class="button-container">
    <button><a href="<%= user_posts_path(@user) %>">See all posts</a></button>
</div>
</body>