config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy]
  end
  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
    resources :likes, only: [:create]
  end

  #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  
  root 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # Attributes
  attribute :title, :string
  attribute :text, :text
  attribute :comments_couter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0

  # Callback
  after_save :update_user_posts_counter

  # Validations
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  # Methods
  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :find_user

  def index
    @posts = @user.posts
    render json: @posts
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments).paginate(page: params[:page], per_page: 2)
  end

  def show
    @post = Post.includes(comments: :author).find(params[:id])
    @current = current_user
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @new_post = current_user.posts.build(post_parameters)
    respond_to do |format|
      format.html do
        if @new_post.save
          redirect_to user_post_path(current_user, @new_post), notice: 'Post created successfully.'
        else
          flash.now[:alert] = 'Please try again.'
          render :new
        end
      end
    end
  end

  def destroy
    @user = current_user
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(@user), notice: 'Post was successfully deleted.'
  end

  private

  def post_parameters
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/views/posts/_post.html.erb
<%= stylesheet_link_tag 'post', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
<div id="post">
post #<%= post.id %><br>
    <%= post.text %><br>
<p id= "comments-likes">
comments: <%= post.comments_counter? ? post.comments_counter : 0 %> , 
Likes: <%= post.likes_counter? ? post.likes_counter : 0 %>
</p>
<% if can? :destroy, post %>
  <%= link_to "Delete Post", user_post_path(current_user, post), method: :delete, data: {
                    turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: "delete-post-link" %>
<%end%>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>
<nav class="nav">
    <%= link_to "Add New Post", new_user_post_path(@user.id) %>
    <%= link_to "Home", root_path %>
    <%= link_to "Back", :back %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
</nav>

<%= render @user%>
<% @posts.each do |post| %>
    <a href ="<%= user_post_path(@user, post)%>"><%= render post%></a>
    <%= "no comments for this post" if post.comments.empty?%>
    <div class="comments">
    <% post.five_most_recent_comments.includes(:author).each do |comment|%>
        <%=render comment%>
    <% end %>
    </div>
    <p id="view-post"><%= link_to 'View Post', user_post_path(@user, post) %></p>
<% end %>
</body>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'post', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>
<h1>Add a new post</h1>
<%= form_with model: @post, url: user_posts_path(@user), method: :post, local: true, scope: :post do |form| %>
   <%= form.label :title %>
  <%= form.text_field :title, required: true %>

  <%= form.label :text %>
  <%= form.text_area :text, required: true %>

  <%= form.submit "Create Post" %>
<% end %>
</body>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'post', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<body>

<nav class="nav">
    <%= link_to "Home", root_path %>
    <%= link_to "Back", :back %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
</nav>

<%= render partial: 'post', locals: { post: @post } %> <br>
<%= "no comments for this post" if @post.comments.empty?%>
<div class="comments">
<% @post.comments.each do |comment|%>
        <%=render comment %>
        <% if can? :delete, comment %>
    <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
  <% end %>
<% end %>
</div>

<div class="like-comment"><%= render "comments/create" %> 

<%if Like.where(author_id: User.first.id, post_id: @post.id).exists?%>
 <p id= "liked">Liked<p>
<%else%>
<%= render "likes/create" %></div>
<%end%>
</body>